### ISSUE TITLE
New HPO and HGNC releases

### ISSUE THREAD

**Issue by peupeubangbang** [aehrc/ontoserver#1]
Can I ask when Ontoserver will load the latest versions of HPO and HGNC? As I note they are from mid-2021 :)

**Comment by jimsteel** [comment]
Hi @peupeubangbang ,
Do you mean in the Ontoserver R4 sandbox server https://r4.ontoserver.csiro.au/fhir, or in some other deployment? Ontoserver as a product ships without content, and although there are some services that we run (the R4 sandbox being one), the content on them is generally provided on a best-effort basis without guarantees.
Jim.
